import express from "express";
import { getOrder } from "../resolvers/order/get-order.js";
import { createOrder } from "../resolvers/order/create-order.js";
import { changeOrder } from "../resolvers/order/change-order.js";
import { deleteOrder } from "../resolvers/order/delete-order.js";
export const orderRouter = express.Router();
orderRouter.get("/", getOrder);
orderRouter.post("/", createOrder);
orderRouter.put("/", changeOrder);
orderRouter.delete("/:id", deleteOrder);
